name: Cypress Tests
on: push
jobs:
  tests-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Start local server
        run: npm start &
      - name: Run Cypress tests
        run: npm test